//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string adminID { get; set; }
        public string email { get; set; }
        public Nullable<int> phone { get; set; }
        public string adminFName { get; set; }
        public string adminLName { get; set; }
    }
}
