//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ISSN { get; set; }
        public string jourID { get; set; }
        public string headline { get; set; }
        public Nullable<System.DateTime> datePub { get; set; }
        public string text { get; set; }
        public string topic { get; set; }
        public string comments { get; set; }
    
        public virtual Journalist Journalist { get; set; }
    }
}
