//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journalist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journalist()
        {
            this.Articles = new HashSet<Article>();
            this.ProfileImgs = new HashSet<ProfileImg>();
        }
    
        public string JourID { get; set; }
        public string officeName { get; set; }
        public string jourFName { get; set; }
        public string jourLName { get; set; }
        public Nullable<System.DateTime> jourDob { get; set; }
        public Nullable<int> phone { get; set; }
        public string email { get; set; }
        public string officeStreet { get; set; }
        public string officeSuburb { get; set; }
        public string officeState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileImg> ProfileImgs { get; set; }
    }
}
